name: openff-nagl-test
channels:
  - conda-forge
  - defaults
dependencies:
    # Base depends
  - python
  - pip
  - importlib_resources

  # UI
  - click
  - click-option-group
  - rich
  - tqdm

  # chemistry
  - openff-toolkit-base >=0.11.1
  - openff-units
  - pydantic <3
  - rdkit
  - scipy

  # files
  - pyyaml

  # gcn
  - pytorch >=2.0
  - pytorch-lightning

  # Testing
  - pytest
  - pytest-cov
  - pytest-xdist
  - codecov
