name: Include OpenEye
description: Include OpenEye
inputs:
  openeye-license-text:
    description: OpenEye license
    required: true
  openeye-license-file:
    description: License file
    required: true
    default: ${{ github.workspace }}/oe_license.txt
  shell:
    description: Desired shell
    required: true
    default: bash -l {0}

runs:
  using: "composite"
  steps:
    - name: Install OpenEye
      shell: ${{ inputs.shell }}
      run: |
        micromamba install -y -c openeye openeye-toolkits

    - name: Make oe_license.txt file from GH org secret "OE_LICENSE"
      shell: ${{ inputs.shell }}
      run: |
        echo "${{ inputs.openeye-license-text }}" > ${{ inputs.openeye-license-file }}
        export OE_LICENSE=${{ inputs.openeye-license-file }}

    - name: Test OpenEye
      shell: ${{ inputs.shell }}
      run: |
        python -c "from openff.toolkit.utils.toolkits import OPENEYE_AVAILABLE; assert OPENEYE_AVAILABLE"