partial_charge_method: am1

# base
convolution_architecture: SAGEConv
postprocess_layer: compute_partial_charges
use_cached_data: True

# hyperparameters
# (will be overridden in hyperparameter search)
activation_function: ReLU
learning_rate: 0.001
n_convolution_hidden_features: 128
n_convolution_layers: 3
n_readout_hidden_features: 128
n_readout_layers: 4

# features
atom_features:
  - AtomicElement:
      categories: ["C", "O", "H", "N", "S", "F", "Br", "Cl", "I", "P"]
  - AtomConnectivity
  - AtomAverageFormalCharge
  - AtomHybridization
  - AtomInRingOfSize: 3
  - AtomInRingOfSize: 4
  - AtomInRingOfSize: 5
  - AtomInRingOfSize: 6
bond_features:
  - BondInRingOfSize: 3
  - BondInRingOfSize: 4
  - BondInRingOfSize: 5
  - BondInRingOfSize: 6

# data
training-set-paths:
  - ../labelled-data/labelled-enamine-10240-short.sqlite
validation-set-paths:
  - ../labelled-data/labelled-enamine-10240-short.sqlite
test-set-paths:
  - ../labelled-data/labelled-enamine-10240-short.sqlite
training_batch_size: 1000
validation_batch_size: 1000
test_batch_size: 1000