name: gnn-charge-models-docs
channels:
  - conda-forge
dependencies:
    # Base depends
  - python
  - pip

  - sphinx

    # Pip-only installs
  - pip:
    - git+https://github.com/openforcefield/openff-sphinx-theme.git@main
